# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=255)),
                ('quality', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FighterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('explain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kof.SkillType'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kof.FighterType'),
        ),
    ]
